# -*- coding: utf-8 -*-
"""Reto_9_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zp_rN9r1eXyglW9mDUQkQiV703X498XA
"""

# Ejemplo punto 3, taller 1, peso 5 sin args*
masa_gina: int =6
masa_galo: int=7
masa_poll: int=1

#Se definieron las masas de las gallinas, gallos, pollitos, como constantes

import math as m #importar libreria math

def carne_(gallina:float, gallo:float, pollitos:float) -> float:
  c_carne = (gallina*masa_gina + gallo*masa_galo + pollitos*masa_poll)
  return c_carne  #se definio la variable de cantidad de carne


if __name__ == "__main__":
  gallina = float(input("Cantidad de gallinas:"))
  gallo = float(input("Cantidad de gallos:"))
  pollitos = float(input("Cantidad de pollitos:"))
  carne_total = carne_(gallina, gallo, pollitos)
  print("La cantidad de carne es " + str(carne_total)+ " kilos") #se puso condicional if que defina las variables con teclado y me imprima la cantidad total de carne

# Ejemplo punto 7, taller 1, promedio 5 números con args*
def peso_t(*args)-> int:
  peso = (6*gallina)+(7*gallo)+(pollo)
  return peso

if __name__ == "__main__":
  gallina = int(input("Ingrese numero de gallinas: "))
  gallo = int(input("Ingrese numero de gallos: "))
  pollo = int(input("Ingrese numero de pollos: "))
  print("El promedio de los cinco números es " + str(peso_t(gallina, gallo, pollo))+ " kilos")

# Ejemplo punto 7, taller 1, promedio 5 números sin args*
def numeros(numero_1:float, numero_2:float, numero_3:float, numero_4:float, numero_5: float) -> float:
  promedio = ((numero_1 + numero_2 + numero_3 + numero_4 + numero_5)/5)
  return promedio  #se definio la variable para calcular el promedio

if __name__ == "__main__":
  numero_1 = float(input("Ingresa el número 1:"))
  numero_2 = float(input("Ingresa el número 2:"))
  numero_3 = float(input("Ingresa el número 3:"))
  numero_4 = float(input("Ingresa el número 4:"))
  numero_5 = float(input("Ingresa el número 5:"))
  prom = numeros(numero_1, numero_2, numero_3, numero_4, numero_5)
  print("El promedio de los 5 numeros es " +str(prom))

# Ejemplo punto 7, taller 1, promedio 5 números con args*
def prom_numeros(*args)-> int:
  suma : int = 0
  n : int = 0
  for num in args:
    suma +=  num
    n += 1
  suma = suma/n
  return suma

if __name__ == "__main__":
  a = int(input("Ingrese numero a: "))
  b = int(input("Ingrese numero b: "))
  c = int(input("Ingrese numero c: "))
  d = int(input("Ingrese numero d: "))
  e = int(input("Ingrese numero e: "))
  print("El promedio de los cinco números es " + str(prom_numeros(a, b, c, d, e)))

# Ejemplo punto 7, taller 1, promedio multiplicativo 5 números sin args*
def numeros_(numero_1:float, numero_2:float, numero_3:float, numero_4:float, numero_5: float) -> float:
    promedio_multiplicativo = ((numero_1*numero_2*numero_3*numero_4*numero_5)**0.2)
    return promedio_multiplicativo #se definio la variable para calcular el promedio multiplicativo
if __name__ == "__main__":
  numero_1 = float(input("Ingresa el número 1:"))
  numero_2 = float(input("Ingresa el número 2:"))
  numero_3 = float(input("Ingresa el número 3:"))
  numero_4 = float(input("Ingresa el número 4:"))
  numero_5 = float(input("Ingresa el número 5:"))
  prom_mult = numeros_(numero_1, numero_2, numero_3, numero_4, numero_5)
  print("El promedio multiplicativo de los 5 números es " +str(prom_mult))

# Ejemplo punto 7, taller 1, promedio 5 números con args*
def promult_numeros(*args)-> int:
  mult : int = 1
  n : int = 0
  for num in args:
    mult *=  num
    n += 1
  mult = mult**(1/n)
  return mult

if __name__ == "__main__":
  a = int(input("Ingrese numero a: "))
  b = int(input("Ingrese numero b: "))
  c = int(input("Ingrese numero c: "))
  d = int(input("Ingrese numero d: "))
  e = int(input("Ingrese numero e: "))
  print("El promedio de los cinco números es " + str(promult_numeros(a, b, c, d, e)))