# -*- coding: utf-8 -*-
"""Reto_9_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynPwus6-FxTHvtx0QOxUY4dvq2fTXjLf
"""

#Punto 3
def potencia_num(bas, exp):
  if exp == 0:
    return 1
  elif exp == 1:
    return bas
  elif bas == 1:
    return bas
  else:
    return bas * potencia_num(bas, exp - 1)

if __name__ == "__main__":
  exp = int(input("Ingrese la potencia: "))
  bas = float(input("Ingrese la base: "))
  potencia = potencia_num(bas, exp)
  print("Si elevamos "  +str(bas)+  " a " + str(exp) + " es igual a " + str(potencia))