# -*- coding: utf-8 -*-
"""Reto_9_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvPQjPZF5svlEV0t4eEm1Up-xMMPBzLE
"""

import time
bandera = True
a : int = 1
while bandera == True:
  start_time = time.time()
  def fiboRecursivo(n : int )-> int:
    if n <=1:
      # caso base
      return 1
    else:
      # condicion
      return fiboRecursivo(n-1)+fiboRecursivo(n-2)

  if __name__ == "__main__":
    num = a
    serieFibo = fiboRecursivo(num)
    end_time = time.time()
    timer = end_time - start_time

  if timer > 10.0:
    break
  else:
    a=a+1
    #print("La serie de Fibonacci hasta " + str(num) + " es " + str(serieFibo))
    #print("Su tiempo de ejecución fue de +str(timer)) Estos dos por si quires analizar cada tiempo
print("La serie de Fibonacci hasta " + str(num) + " es " + str(serieFibo))
print("A partir de aqui considerar tiempo considerable")
print("Su tiempo de ejecución fue de : " +str(timer))